declare module '@actions/DashboardController'
declare module '@actions/NotificationsController'
declare module '@actions/ClientController'
declare module '@actions/InvoiceController'
declare module '@actions/ProjectController'
declare module '@actions/TaskController'
declare module '@actions/ApprovalController'
